### ISSUE TITLE
Consistent values of node HashRing and python HashRing

### ISSUE THREAD

**Issue by cypreess** [bnoguchi/node-hash-ring#14]
Is there any chance that nodejs hash ring could return exactly the same mapping as  python-hashring (http://pypi.python.org/pypi/hash_ring/) module?

I have tested this case and results from each code differs :(

I am badly in need of consistent way doing of hashring in nodejs and python at the same time.  I would appreciate any help. 

EDIT: So here is how I test it

from nodejs

``` javascript
var HashRing = require("hash_ring");

var ring = new HashRing({
    '0.0.0.1':1,
    '0.0.0.2':2,
    '0.0.0.3':3,
    '0.0.0.4':4,
    '0.0.0.5':5

 });

for (var i=0; i < 1000; i++){
    console.log(i + ' ' + ring.getNode(i ));
}
```

from python

``` python
from hash_ring import HashRing

weights = {
    '0.0.0.1': 1,
    '0.0.0.2': 2,
    '0.0.0.3': 3,
    '0.0.0.4': 4,
    '0.0.0.5': 5
}

ring = HashRing(weights.keys(), weights)

for i in xrange(1000):
    print i, ring.get_node(str(i))

```

The result set differs in 1/3 keys

``` shell
$ diff -U 0 test_js.txt test_py.txt | grep -v ^@ | wc -l
     364
```

**Comment by bnoguchi** [comment]
I wasn't planning on it. If you want to submit a pull request, I'll take a look.

##
